CREATE TABLE [dbo].[UserPOI]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FK_POI] INT NOT NULL, 
	[FK_UserTour] INT NOT NULL, 
    [Date] DATETIME NOT NULL, 
    CONSTRAINT [FK_UserPOI_POI] FOREIGN KEY ([FK_POI]) REFERENCES [POI]([Id]),
	CONSTRAINT [FK_UserPOI_UserTour] FOREIGN KEY ([FK_UserTour]) REFERENCES [UserTour]([Id])
)
