//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelBuddy5.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPOI
    {
        public int Id { get; set; }
        public int FK_POI { get; set; }
        public int FK_UserTour { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual POI POI { get; set; }
        public virtual UserTour UserTour { get; set; }
    }
}
